// ╔══════════════════════════════════════════════════════════╗
// ║         QUIZ DATA FILE — आदित्य कोचिंग सेंटर           ║
// ║                                                          ║
// ║  Quiz add करने का तरीका:                                ║
// ║  file:'' → file:'1quiz.html'  (filename डालो)           ║
// ║  file:'' मतलब quiz अभी नहीं बनी                         ║
// ╚══════════════════════════════════════════════════════════╝

var QUIZ_DATA = {

  // ════════════════════════════════
  //         CLASS 10TH
  // ════════════════════════════════
  c10: [

    // 📐 गणित
    {id:'10-math', icon:'📐', name:'गणित', chapters:[
      {name:'वास्तविक संख्याएँ',              file:'1Quiz.html'},
      {name:'बहुपद',                          file:''},
      {name:'द्विघात समीकरण',                 file:''},
      {name:'दो चर वाले रैखिक समीकरण',        file:''},
      {name:'अंकगणित श्रेढ़ी',                 file:''},
      {name:'त्रिभुज',                         file:''},
      {name:'निर्देशांक ज्यामिति',              file:''},
      {name:'त्रिकोणमिति',                     file:''},
      {name:'त्रिकोणमिति के अनुप्रयोग',        file:''},
      {name:'वृत्त',                           file:''},
      {name:'रचनाएँ',                          file:''},
      {name:'वृत्तों से संबंधित क्षेत्रफल',    file:''},
      {name:'पृष्ठीय क्षेत्रफल और आयतन',       file:''},
      {name:'सांख्यिकी',                       file:''},
      {name:'प्रायिकता',                        file:''},
    ]},

    // 🔬 विज्ञान
    {id:'10-sci', icon:'🔬', name:'विज्ञान', chapters:[
      {name:'रासायनिक अभिक्रियाएँ',            file:''},
      {name:'अम्ल, क्षार और लवण',              file:''},
      {name:'धातु और अधातु',                   file:''},
      {name:'कार्बन और उसके यौगिक',            file:''},
      {name:'तत्वों का वर्गीकरण',              file:''},
      {name:'जैव प्रक्रम',                     file:''},
      {name:'नियंत्रण और समन्वय',              file:''},
      {name:'जीव जनन कैसे करते हैं',           file:''},
      {name:'आनुवंशिकता',                      file:''},
      {name:'प्रकाश – परावर्तन',               file:''},
      {name:'मानव नेत्र',                      file:''},
      {name:'विद्युत',                         file:''},
      {name:'विद्युत धारा के चुंबकीय प्रभाव',  file:''},
      {name:'ऊर्जा के स्रोत',                  file:''},
      {name:'हमारा पर्यावरण',                  file:''},
    ]},

    // 📖 हिंदी
    {id:'10-hindi', icon:'📖', name:'हिंदी', chapters:[
      {name:'पद – कबीर',                       file:''},
      {name:'राम-लक्ष्मण-परशुराम संवाद',       file:''},
      {name:'सवैया और कवित्त',                 file:''},
      {name:'आत्मकथ्य',                        file:''},
      {name:'उत्साह और अट नहीं रही',           file:''},
      {name:'यह दंतुरहित मुस्कान',              file:''},
      {name:'छाया मत छूना',                    file:''},
      {name:'कन्यादान',                         file:''},
      {name:'संगतकार',                          file:''},
      {name:'नेताजी का चश्मा',                  file:''},
      {name:'बालगोबिन भगत',                    file:''},
      {name:'लखनवी अंदाज़',                    file:''},
      {name:'मानवीय करुणा की दिव्य चमक',       file:''},
      {name:'एक कहानी यह भी',                  file:''},
      {name:'स्त्री शिक्षा के विरोधी',          file:''},
    ]},

    // 🌍 सामाजिक विज्ञान
    {id:'10-sst', icon:'🌍', name:'सामाजिक विज्ञान', chapters:[
      {name:'यूरोप में राष्ट्रवाद',             file:''},
      {name:'भारत में राष्ट्रवाद',              file:''},
      {name:'भूमंडलीकृत विश्व का बनना',        file:''},
      {name:'औद्योगीकरण का युग',               file:''},
      {name:'मुद्रण संस्कृति',                  file:''},
      {name:'संसाधन एवं विकास',                file:''},
      {name:'वन और वन्य जीव',                  file:''},
      {name:'जल संसाधन',                       file:''},
      {name:'कृषि',                            file:''},
      {name:'खनिज तथा ऊर्जा संसाधन',          file:''},
      {name:'विनिर्माण उद्योग',                 file:''},
      {name:'राष्ट्रीय अर्थव्यवस्था',           file:''},
      {name:'सत्ता की साझेदारी',               file:''},
      {name:'विकास',                           file:''},
      {name:'मुद्रा और साख',                   file:''},
    ]},

    // 🇬🇧 English
    {id:'10-eng', icon:'🇬🇧', name:'English', chapters:[
      {name:'A Letter to God',                  file:''},
      {name:'Nelson Mandela',                   file:''},
      {name:'Two Stories About Flying',         file:''},
      {name:'From the Diary of Anne Frank',     file:''},
      {name:'Glimpses of India',                file:''},
      {name:'Mijbil the Otter',                 file:''},
      {name:'Madam Rides the Bus',              file:''},
      {name:'The Sermon at Benares',            file:''},
      {name:'The Proposal',                     file:''},
      {name:'A Triumph of Surgery',             file:''},
      {name:"The Thief's Story",                file:''},
      {name:'The Midnight Visitor',             file:''},
      {name:'A Question of Trust',              file:''},
      {name:'Footprints Without Feet',          file:''},
      {name:'The Making of a Scientist',        file:''},
    ]},

    // 🪔 संस्कृत
    {id:'10-sans', icon:'🪔', name:'संस्कृत', chapters:[
      {name:'शुचिपर्यावरणम्',                  file:''},
      {name:'बुद्धिर्बलवती सदा',               file:''},
      {name:'शिशुलालनम्',                      file:''},
      {name:'जननी तुल्यवत्सला',               file:''},
      {name:'सुभाषितानि',                       file:''},
      {name:'सौहार्दं प्रकृतेः शोभा',           file:''},
      {name:'विचित्रः साक्षी',                  file:''},
      {name:'सूक्तयः',                          file:''},
      {name:'भारतीयसंस्काराः',                  file:''},
      {name:'नैतिकता',                          file:''},
      {name:'समवायो हि दुर्जयः',               file:''},
      {name:'विद्या ददाति विनयम्',             file:''},
      {name:'अनुशासनम्',                        file:''},
      {name:'परोपकाराय',                        file:''},
      {name:'प्रत्यभिज्ञानम्',                 file:''},
    ]},

  ],

  // ════════════════════════════════
  //         CLASS 12TH
  // ════════════════════════════════
  c12: [

    {id:'12-math', icon:'📐', name:'गणित', chapters:[
      {name:'संबंध और फलन',                    file:''},
      {name:'प्रतिलोम त्रिकोणमितीय फलन',       file:''},
      {name:'आव्यूह',                          file:''},
      {name:'सारणिक',                          file:''},
      {name:'सांतत्य और अवकलनीयता',            file:''},
      {name:'अवकलज के अनुप्रयोग',              file:''},
      {name:'समाकलन',                          file:''},
      {name:'समाकलनों के अनुप्रयोग',           file:''},
      {name:'अवकल समीकरण',                    file:''},
      {name:'सदिश बीजगणित',                   file:''},
      {name:'त्रिविमीय ज्यामिति',               file:''},
      {name:'रैखिक प्रोग्रामन',                file:''},
      {name:'प्रायिकता',                        file:''},
      {name:'द्विपद बंटन',                     file:''},
      {name:'परिशिष्ट',                        file:''},
    ]},

    {id:'12-phy', icon:'⚡', name:'भौतिकी', chapters:[
      {name:'वैद्युत आवेश और क्षेत्र',          file:''},
      {name:'स्थिरवैद्युत विभव',               file:''},
      {name:'धारा विद्युत',                    file:''},
      {name:'गतिमान आवेश और चुंबकत्व',         file:''},
      {name:'चुंबकत्व और द्रव्य',              file:''},
      {name:'वैद्युत चुंबकीय प्रेरण',           file:''},
      {name:'प्रत्यावर्ती धारा',               file:''},
      {name:'वैद्युत चुंबकीय तरंगें',           file:''},
      {name:'किरण प्रकाशिकी',                 file:''},
      {name:'तरंग प्रकाशिकी',                 file:''},
      {name:'विकिरण और द्रव्य की प्रकृति',     file:''},
      {name:'परमाणु',                          file:''},
      {name:'नाभिक',                           file:''},
      {name:'अर्धचालक इलेक्ट्रॉनिकी',          file:''},
      {name:'संचार व्यवस्था',                  file:''},
    ]},

    {id:'12-chem', icon:'🧪', name:'रसायन विज्ञान', chapters:[
      {name:'ठोस अवस्था',                      file:''},
      {name:'विलयन',                           file:''},
      {name:'वैद्युत रसायन',                   file:''},
      {name:'रासायनिक बलगतिकी',               file:''},
      {name:'पृष्ठ रसायन',                     file:''},
      {name:'तत्वों के निष्कर्षण के सिद्धांत', file:''},
      {name:'p-ब्लॉक के तत्व',                file:''},
      {name:'d और f ब्लॉक के तत्व',           file:''},
      {name:'उपसहसंयोजन यौगिक',               file:''},
      {name:'हैलोऐल्केन और हैलोऐरीन',         file:''},
      {name:'ऐल्कोहॉल, फ़िनॉल और ईथर',       file:''},
      {name:'ऐल्डिहाइड, कीटोन, कार्बोक्सिलिक अम्ल', file:''},
      {name:'ऐमीन',                            file:''},
      {name:'जैव अणु',                         file:''},
      {name:'बहुलक और रसायन',                 file:''},
    ]},

    {id:'12-bio', icon:'🌿', name:'जीव विज्ञान', chapters:[
      {name:'जीवों में जनन',                   file:''},
      {name:'पुष्पी पादपों में लैंगिक जनन',    file:''},
      {name:'मानव जनन',                        file:''},
      {name:'जनन स्वास्थ्य',                   file:''},
      {name:'वंशागति और विविधता',              file:''},
      {name:'वंशागति का आणविक आधार',          file:''},
      {name:'विकास',                           file:''},
      {name:'मानव स्वास्थ्य और रोग',           file:''},
      {name:'खाद्य उत्पादन में वृद्धि',        file:''},
      {name:'मानव कल्याण में सूक्ष्मजीव',      file:''},
      {name:'जैव प्रौद्योगिकी के सिद्धांत',    file:''},
      {name:'जैव प्रौद्योगिकी के उपयोग',       file:''},
      {name:'जीव और समष्टियाँ',               file:''},
      {name:'पारितंत्र',                        file:''},
      {name:'जैव विविधता और संरक्षण',          file:''},
    ]},

    {id:'12-hindi', icon:'📖', name:'हिंदी', chapters:[
      {name:'आत्मपरिचय',                       file:''},
      {name:'पतंग',                            file:''},
      {name:'कविता के बहाने',                  file:''},
      {name:'कैमरे में बंद अपाहिज',            file:''},
      {name:'सहर्ष स्वीकारा है',               file:''},
      {name:'उषा',                             file:''},
      {name:'बादल राग',                         file:''},
      {name:'कवितावली',                        file:''},
      {name:'रुबाइयाँ',                         file:''},
      {name:'छोटा मेरा खेत',                   file:''},
      {name:'भक्तिन',                          file:''},
      {name:'बाजार दर्शन',                     file:''},
      {name:'काले मेघा पानी दे',               file:''},
      {name:'पहलवान की ढोलक',                 file:''},
      {name:'चार्ली चैप्लिन',                   file:''},
    ]},

    {id:'12-eng', icon:'🇬🇧', name:'English', chapters:[
      {name:'The Last Lesson',                  file:''},
      {name:'Lost Spring',                      file:''},
      {name:'Deep Water',                       file:''},
      {name:'The Rattrap',                      file:''},
      {name:'Indigo',                           file:''},
      {name:'Poets and Pancakes',               file:''},
      {name:'The Interview',                    file:''},
      {name:'Going Places',                     file:''},
      {name:'My Mother at Sixty-six',           file:''},
      {name:'An Elementary School',             file:''},
      {name:'Keeping Quiet',                    file:''},
      {name:'A Thing of Beauty',                file:''},
      {name:'A Roadside Stand',                 file:''},
      {name:"Aunt Jennifer's Tigers",           file:''},
      {name:'The Tiger King',                   file:''},
    ]},

    {id:'12-sans', icon:'🪔', name:'संस्कृत', chapters:[
      {name:'अपठित-अवबोधनम्',                  file:''},
      {name:'पाठ्यपुस्तक गद्यांश',             file:''},
      {name:'पाठ्यपुस्तक पद्यांश',             file:''},
      {name:'रचनात्मक कार्य',                  file:''},
      {name:'व्याकरण – संधि',                  file:''},
      {name:'व्याकरण – समास',                  file:''},
      {name:'व्याकरण – कारक',                  file:''},
      {name:'व्याकरण – प्रत्यय',               file:''},
      {name:'व्याकरण – उपसर्ग',               file:''},
      {name:'व्याकरण – वाच्य',                 file:''},
      {name:'अनुवाद',                          file:''},
      {name:'पत्र लेखन',                       file:''},
      {name:'निबंध लेखन',                      file:''},
      {name:'सूक्तिपरक वाक्य',                 file:''},
      {name:'व्याकरण – अव्यय',                file:''},
    ]},

  ],

  // ════════════════════════════════
  //       COMPETITIVE EXAMS
  // ════════════════════════════════
  comp: [

    {id:'comp-math', icon:'📐', name:'गणित', chapters:[
      {name:'संख्या पद्धति',                   file:''},
      {name:'सरलीकरण',                         file:''},
      {name:'LCM और HCF',                     file:''},
      {name:'औसत',                             file:''},
      {name:'प्रतिशत',                         file:''},
      {name:'लाभ और हानि',                     file:''},
      {name:'अनुपात और समानुपात',              file:''},
      {name:'साझेदारी',                         file:''},
      {name:'समय और कार्य',                    file:''},
      {name:'समय और दूरी',                     file:''},
      {name:'साधारण ब्याज',                    file:''},
      {name:'चक्रवृद्धि ब्याज',               file:''},
      {name:'क्षेत्रमिति',                      file:''},
      {name:'बीजगणित',                         file:''},
      {name:'आँकड़ों की व्याख्या',             file:''},
    ]},

    {id:'comp-gk', icon:'🧠', name:'सामान्य ज्ञान (GK)', chapters:[
      {name:'भारतीय इतिहास',                   file:''},
      {name:'भारतीय संविधान',                  file:''},
      {name:'भारतीय अर्थव्यवस्था',             file:''},
      {name:'भारतीय भूगोल',                   file:''},
      {name:'विश्व का भूगोल',                  file:''},
      {name:'विज्ञान और प्रौद्योगिकी',         file:''},
      {name:'खेल जगत',                         file:''},
      {name:'पुरस्कार और सम्मान',              file:''},
      {name:'महत्वपूर्ण दिवस',                 file:''},
      {name:'राष्ट्रीय/अंतर्राष्ट्रीय संगठन', file:''},
      {name:'करंट अफेयर्स 2024',               file:''},
      {name:'बिहार विशेष GK',                  file:''},
      {name:'संक्षिप्त नाम (Abbreviations)',   file:''},
      {name:'प्रमुख योजनाएँ',                  file:''},
      {name:'विविध',                           file:''},
    ]},

    {id:'comp-sci', icon:'🔬', name:'सामान्य विज्ञान', chapters:[
      {name:'पदार्थ और उसकी अवस्थाएँ',        file:''},
      {name:'परमाणु संरचना',                   file:''},
      {name:'रासायनिक अभिक्रियाएँ',            file:''},
      {name:'अम्ल, क्षार और लवण',              file:''},
      {name:'धातु और अधातु',                   file:''},
      {name:'कार्बन यौगिक',                    file:''},
      {name:'गति और बल',                      file:''},
      {name:'कार्य और ऊर्जा',                  file:''},
      {name:'प्रकाश',                          file:''},
      {name:'विद्युत',                         file:''},
      {name:'चुंबकत्व',                        file:''},
      {name:'जीव विज्ञान – कोशिका',           file:''},
      {name:'मानव शरीर',                      file:''},
      {name:'पोषण और रोग',                    file:''},
      {name:'पर्यावरण',                        file:''},
    ]},

    {id:'comp-hindi', icon:'📖', name:'हिंदी', chapters:[
      {name:'संधि',                            file:''},
      {name:'समास',                            file:''},
      {name:'उपसर्ग और प्रत्यय',              file:''},
      {name:'वाक्य शुद्धि',                   file:''},
      {name:'मुहावरे और लोकोक्तियाँ',         file:''},
      {name:'पर्यायवाची शब्द',                file:''},
      {name:'विलोम शब्द',                     file:''},
      {name:'अनेकार्थी शब्द',                 file:''},
      {name:'रिक्त स्थान',                    file:''},
      {name:'अपठित गद्यांश',                  file:''},
      {name:'पत्र लेखन',                       file:''},
      {name:'निबंध लेखन',                      file:''},
      {name:'काल',                             file:''},
      {name:'कारक',                            file:''},
      {name:'वाच्य',                           file:''},
    ]},

    {id:'comp-eng', icon:'🇬🇧', name:'English', chapters:[
      {name:'Synonyms',                         file:''},
      {name:'Antonyms',                         file:''},
      {name:'One Word Substitution',            file:''},
      {name:'Idioms and Phrases',               file:''},
      {name:'Fill in the Blanks',               file:''},
      {name:'Error Detection',                  file:''},
      {name:'Sentence Improvement',            file:''},
      {name:'Active/Passive Voice',             file:''},
      {name:'Direct/Indirect Speech',           file:''},
      {name:'Reading Comprehension',            file:''},
      {name:'Cloze Test',                       file:''},
      {name:'Tenses',                           file:''},
      {name:'Prepositions',                     file:''},
      {name:'Articles',                         file:''},
      {name:'Vocabulary',                       file:''},
    ]},

    {id:'comp-reason', icon:'💡', name:'तर्कशक्ति (Reasoning)', chapters:[
      {name:'श्रृंखला (Series)',                file:''},
      {name:'सादृश्यता (Analogy)',              file:''},
      {name:'वर्गीकरण (Classification)',        file:''},
      {name:'कोडिंग-डिकोडिंग',                 file:''},
      {name:'रक्त संबंध',                      file:''},
      {name:'दिशा परीक्षण',                    file:''},
      {name:'बैठने की व्यवस्था',               file:''},
      {name:'क्रम और रैंकिंग',                 file:''},
      {name:'घड़ी और कैलेंडर',                file:''},
      {name:'पहेली (Puzzles)',                  file:''},
      {name:'वेन आरेख',                        file:''},
      {name:'कथन और निष्कर्ष',                file:''},
      {name:'न्याय निगमन',                     file:''},
      {name:'आकृति – गिनना',                  file:''},
      {name:'दर्पण और जल छवि',                file:''},
    ]},

    {id:'comp-hist', icon:'🏛️', name:'इतिहास', chapters:[
      {name:'प्राचीन भारत – सिंधु सभ्यता',    file:''},
      {name:'वैदिक काल',                       file:''},
      {name:'मौर्य साम्राज्य',                 file:''},
      {name:'गुप्त काल',                       file:''},
      {name:'दिल्ली सल्तनत',                  file:''},
      {name:'मुगल साम्राज्य',                  file:''},
      {name:'मराठा साम्राज्य',                 file:''},
      {name:'ब्रिटिश शासन',                   file:''},
      {name:'1857 की क्रांति',                 file:''},
      {name:'भारतीय राष्ट्रीय आंदोलन',        file:''},
      {name:'गाँधी युग',                       file:''},
      {name:'स्वतंत्रता और विभाजन',            file:''},
      {name:'विश्व इतिहास',                   file:''},
      {name:'प्रमुख युद्ध',                    file:''},
      {name:'विविध',                           file:''},
    ]},

    {id:'comp-geo', icon:'🗺️', name:'भूगोल', chapters:[
      {name:'पृथ्वी और ब्रह्मांड',             file:''},
      {name:'भारत की स्थिति और विस्तार',       file:''},
      {name:'भारत की नदियाँ',                 file:''},
      {name:'भारत की पर्वत श्रृंखलाएँ',       file:''},
      {name:'भारत की जलवायु',                 file:''},
      {name:'भारत की मिट्टी',                 file:''},
      {name:'भारत के वन',                     file:''},
      {name:'भारत की कृषि',                   file:''},
      {name:'भारत के खनिज',                   file:''},
      {name:'भारत के उद्योग',                  file:''},
      {name:'भारत की जनसंख्या',               file:''},
      {name:'परिवहन और संचार',                file:''},
      {name:'विश्व का भूगोल',                 file:''},
      {name:'महाद्वीप और महासागर',            file:''},
      {name:'विविध',                           file:''},
    ]},

    {id:'comp-pol', icon:'⚖️', name:'राजनीति विज्ञान', chapters:[
      {name:'भारतीय संविधान – निर्माण',       file:''},
      {name:'संविधान की विशेषताएँ',            file:''},
      {name:'मौलिक अधिकार',                   file:''},
      {name:'नीति निदेशक तत्व',               file:''},
      {name:'राष्ट्रपति',                      file:''},
      {name:'उपराष्ट्रपति और प्रधानमंत्री',   file:''},
      {name:'संसद',                            file:''},
      {name:'उच्चतम न्यायालय',               file:''},
      {name:'राज्य सरकार',                    file:''},
      {name:'स्थानीय स्वशासन',               file:''},
      {name:'निर्वाचन आयोग',                 file:''},
      {name:'राजनीतिक दल',                   file:''},
      {name:'अंतर्राष्ट्रीय संगठन',            file:''},
      {name:'भारत की विदेश नीति',            file:''},
      {name:'विविध',                           file:''},
    ]},

    {id:'comp-eco', icon:'📊', name:'अर्थशास्त्र', chapters:[
      {name:'भारतीय अर्थव्यवस्था – परिचय',    file:''},
      {name:'राष्ट्रीय आय',                    file:''},
      {name:'पंचवर्षीय योजनाएँ',              file:''},
      {name:'कृषि अर्थव्यवस्था',              file:''},
      {name:'उद्योग और व्यापार',              file:''},
      {name:'बैंकिंग और मुद्रा',               file:''},
      {name:'बजट और कर',                      file:''},
      {name:'गरीबी और बेरोजगारी',             file:''},
      {name:'मानव विकास',                     file:''},
      {name:'अंतर्राष्ट्रीय व्यापार',          file:''},
      {name:'WTO और IMF',                    file:''},
      {name:'भारतीय शेयर बाज़ार',             file:''},
      {name:'आर्थिक सुधार',                   file:''},
      {name:'डिजिटल अर्थव्यवस्था',            file:''},
      {name:'विविध',                           file:''},
    ]},

    {id:'comp-comp', icon:'💻', name:'कंप्यूटर', chapters:[
      {name:'कंप्यूटर का परिचय',              file:''},
      {name:'कंप्यूटर की पीढ़ियाँ',           file:''},
      {name:'इनपुट और आउटपुट डिवाइस',        file:''},
      {name:'मेमोरी और स्टोरेज',              file:''},
      {name:'ऑपरेटिंग सिस्टम',               file:''},
      {name:'MS Word',                         file:''},
      {name:'MS Excel',                        file:''},
      {name:'MS PowerPoint',                   file:''},
      {name:'इंटरनेट और नेटवर्क',             file:''},
      {name:'साइबर सुरक्षा',                  file:''},
      {name:'डेटाबेस',                        file:''},
      {name:'प्रोग्रामिंग – परिचय',           file:''},
      {name:'नंबर सिस्टम',                    file:''},
      {name:'HTML बेसिक्स',                   file:''},
      {name:'विविध',                           file:''},
    ]},

  ]

};
